updated workflow with synthetic fix

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -191,8 +191,10 @@ jobs:
           fi
           echo "Running Datadog Synthetic browser test $SYNTH_TEST_ID ...";
           npx datadog-ci synthetics run-tests \
-            --public-id "$SYNTH_TEST_ID" \
-            --fail-on-critical-errors \
-            --fail-on-timeouts || { echo "Synthetic test failed"; exit 1; }
+            -p "$SYNTH_TEST_ID" \
+            --apiKey "$DATADOG_API_KEY" \
+            --appKey "$DATADOG_APP_KEY" \
+            --subdomain "us5" \
+            --datadogSite "us5.datadoghq.com" || { echo "Synthetic test failed"; exit 1; }
           echo "Synthetic test completed.";
      
